meta_product_name: "Josef Kalleya Famous Quotes"
meta_title: "Josef Kalleya, Maltese Artist 1898 - 1998, Famous Quotes, Titbizzi"
meta_description: "Apart from his striking sculptures and drawings, Kalleya's artistic value is also noted in his elocution. This generator attempts to cataloguise some of his most common musings."
meta_image: "jk7.jpg"
facebook_account: "https://www.facebook.com/kalleya"